---
title: "p14"
format: html
author: "Amanda Jaworsky"
embed-resources: true
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
#install.packages("repurrrsive")
library(repurrrsive)
library(jsonlite)
```


```{r}
df4 <- tribble(
  ~x, ~y, ~z,
  "a", list("y-a-1", "y-a-2"), list("z-a-1", "z-a-2"),
  "b", list("y-b-1", "y-b-2", "y-b-3"), list("z-b-1", "z-b-2", "z-b-3")
)

df4 %>% unnest_longer(y)

repos <- tibble(json = gh_repos)

repos %>%
  unnest_longer(json) %>%
  unnest_wider(json) %>%
  select(id, full_name, owner, description) %>%
  unnest_wider(owner, names_sep = "-")

chars <- tibble(json = got_chars)
  
chars %>%
  unnest_wider(json) %>%
  select(id, titles) %>%
  unnest_longer(titles) %>%
  filter(titles != "") %>%
  rename(title = titles)

locations <- gmaps_cities %>%
  unnest_wider(json) %>%
  select(-status) %>%
  unnest_longer(results) %>%
  unnest_wider(results)


```


##Exercises 24.4.4
1.
```{r}
vr <- repos %>%
  unnest_longer(json) %>%
  unnest_wider(json) %>%
  select(updated_at)

##I would roughly estimate sometime in September 2016, it is difficult to tell because there is no actual date, you can just see the most recent editing and updating dates, and none of them are later than 2016-9
```

2. 
```{r}
owners <- repos %>%
  unnest_longer(json) %>%
  unnest_wider(json) %>%
  unnest_longer(owner) %>%
  separate(col = full_name, 
           into = c("username", "tag"),
           sep = "/") %>%
  distinct(username)
```

3. 
```{r}
aliases <- chars %>% 
  unnest_wider(json)%>%
  select(id, aliases) %>%
  unnest_longer(aliases)

allegiances <- chars %>% 
  unnest_wider(json)%>%
  select(id, allegiances) %>%
  unnest_longer(allegiances)

books <- chars %>%
  unnest_wider(json) %>%
  select(id, books) %>%
  unnest_longer(books)
```

4. 
```{r}
tibble(json = got_chars) |> 
  unnest_wider(json) |> 
  select(id, where(is.list)) |> 
  pivot_longer(
    where(is.list), 
    names_to = "name", 
    values_to = "value"
  ) |>  
  unnest_longer(value)

##first they're making a tibble with the data, then they are pulling out the json lists. in the third row they are selecting for ids that have lists in their rows, then in the 4th-8th they're pivoting all of the list rows to a  column where it has the list label and then making a second column that shows the information contained in each list. This works for this data because they are not layered lists and the information is shown pretty clearly, but it might not work in general because it does not follow tidy principles and relies on list identification that might not be universal. 
```


5. 
```{r}
address_components <- gmaps_cities %>%
  unnest_wider(json) %>%
  unnest_longer(results) %>%
  unnest_wider(results) %>%
  unnest_longer(address_components)%>%
  unnest_wider(address_components, names_sep = "_") %>%
  unnest_longer(address_components_types)

#I think the length varies between rows because certain cities have a different number of ways of defining boundaries but I am honestly not sure
```

